### ISSUE TITLE
Blink is not detected when running on USB Hub

### ISSUE THREAD

**Issue by indigo423** [opennms-forge/onmsblink#6]
If the blink is connected to an active USB Hub, it is not detect.

**Comment by christianpape** [comment]
I never had any problems using the blink1 device with a USB hub. Currently my blink1 stick is attached to my monitor's USB port which is connected to a Thunderbolt-3 docking station. The docking station is connected via USB-C to my MacBook. So, I'm sorry, but think your USB hub is the problem.

**Comment by indigo423** [comment]
This was originally reported from Tarus, I've tried to reproduce on a USB Hub on my monitor but worked as expected.

Close this issue with cannot reproduce.
